### ISSUE TITLE
Timeout time limit

### ISSUE THREAD

**Issue by AbdealiJK** [Readify/httpstatus#20]
Would be nice to have a url where we can specify how long we want the response after (Helps to test whether a piece of code times out correctly)

Wonder if thats even possible ?

**Comment by dennisroche** [comment]
That would be useful. Perhaps as a part of the query string, e.g. `http://httpstat.us/200?wait=3000`

**Comment by balarajagopal** [comment]
I made this change and have a pull request for it here https://github.com/Readify/httpstatus/pull/30

**Comment by balarajagopal** [comment]
This feature is live now
http://httpstat.us/200?sleep=5000

**Comment by AbdealiJK** [comment]
Awesome!

**Comment by kjacobsen** [comment]
Quick question, is there a maximum value and protections to ensure that this cannot result in a DOS of the site?

**Comment by aaronpowell** [comment]
@kjacobsen Yes. https://github.com/Readify/httpstatus/blob/master/src/Teapot.Web/Controllers/StatusController.cs#L14

**Comment by kjacobsen** [comment]
Awesome, thanks for letting me know.

**Comment by aaronpowell** [comment]
@kjacobsen also documented on the home page ;) http://httpstat.us/
