### ISSUE TITLE
Way to return JSON?

### ISSUE THREAD

**Issue by gregpinero** [Readify/httpstatus#22]

**Comment by aaronpowell** [comment]
On any particular end point? Do you want some particular JSON structure? Happy to accept a PR 😄

**Comment by gregpinero** [comment]
Really just anything parse-able would be fine.  Ideally the 200 endpoint.  Just an idea.

**Comment by aaronpowell** [comment]
Done via https://github.com/Readify/httpstatus/commit/4c3b4da629f7da6f4a25e54fc62eb1606ca95c11
