### ISSUE TITLE
Special handling for CORS preflight headers?

### ISSUE THREAD

**Issue by tmo-trustpilot** [Readify/httpstatus#25]
It would probably have to be another route, but it'd be cool if we could test a successful OPTIONs response with CORS headers and then get the status code on any non-OPTIONS requests.

Something like: http://httpstat.us/400/cors

For an `OPTIONS` request would have to echo the values from `Origin`, `Access-Control-Request-Method` and `Access-Control-Request-Headers` if present or use `*` otherwise. Response status code would always be 200.

For any other request type return the correct status code and `*` for the CORS headers.

Happy to help out with code if this is something you want to support.

**Comment by aaronpowell** [comment]
I don't see why we couldn't add it, if you want to get cracking on the PR I'm more than happy to have a review of it look to get it merged :)

**Comment by robdmoore** [comment]
I wonder if we want the ability to be able to control whether the response contains a valid cors for the origin provided, vs * vs an invalid one vs blocking an options request.

I also wonder if we want to somehow support the other cors headers like allow methods and headers?


On 3 Feb 2017, at 5:44 am, Aaron Powell <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see why we couldn't add it, if you want to get cracking on the PR I'm more than happy to have a review of it look to get it merged :)

**Comment by aaronpowell** [comment]
I'm pretty sure that we've got the most common CORS scenarios supported, so closing this out.
