### ISSUE TITLE
Can't compile Teapot solution

### ISSUE THREAD

**Issue by splatteredbits** [Readify/httpstatus#27]
I'm getting compilation errors in the `global.asax.cs` file's `Application_BeginRequest` function when I try to compile the Teapot solution (I'm trying to rollout an internal version of httpstat.us).

> Error	1	The type or namespace name 'EventArgs' could not be found (are you missing a using directive or an assembly reference?)	F:\Build\httpstatus-master\src\Teapot.Web\Global.asax.cs	40	64	Teapot.Web

When I comment out that function, the solution builds and it appears to be running OK. 

It appears there may be missing namespace declarations at the top. If I add

    using System;
    using System.Web;

I'm left with one error:

> Error	1	'System.Web.HttpResponse' does not contain a definition for 'setHeader' and no extension method 'setHeader' accepting a first argument of type 'System.Web.HttpResponse' could be found (are you missing a using directive or an assembly reference?)	F:\Build\httpstatus-master\src\Teapot.Web\Global.asax.cs	47	30	Teapot.Web

I could change the `setHeader` function call to `AddHeader`, but I'm afraid that these missing namespaces are because the solution uses a different API than System and System.Web.

**Comment by aaronpowell** [comment]
Well, that's been broken for a while 😬 

Should be fixed in 1f4da07
