### ISSUE TITLE
Published policy on logs and privacy/security

### ISSUE THREAD

**Issue by nathankurtyka** [Readify/httpstatus#34]
This service is a great idea.

But one item that may limit adoption is the lack of (any) detail about what's done with the logs. This service would be much more approachable if you could demonstrate you were /dev/null'ing all logs.

**Comment by tathamoddie** [comment]
I can say it: we have no interest in logs.

How would we demonstrate that in a satisfactory way?

**Comment by nathankurtyka** [comment]
I think just stating that on the website would be great (because I'm probably not the first person who's wondered)

In the future, an even more reassuring tactic would be to actually implement no logging. Even if this is not demonstrable, publicly stating it is always reassuring.

**Comment by aaronpowell** [comment]
@nathankurtyka do you have any thoughts on how we could demonstrate this to your satisfaction beyond what we're currently doing? Otherwise I'd like to close this.

**Comment by nathankurtyka** [comment]
What about just adding this as an FAQ to the website?
