### ISSUE TITLE
Request: Update redirect endpoints to use https

### ISSUE THREAD

**Issue by BaldvinTh** [Readify/httpstatus#36]
Could redirects for the following endpoints be updated to use `https://httpstat.us` instead of `http://httpstat.us` since TLS is now available?

- [301](https://github.com/Readify/httpstatus/blob/4c3b4da629f7da6f4a25e54fc62eb1606ca95c11/src/Teapot.Web/Models/StatusCodeResults.cs#L68)
- 302
- 303
- 305
- 307
- 308

Current implementation can cause a Mixed Content error in JavaScript applications, and thus have the request blocked.

**Comment by aaronpowell** [comment]
Hmm, probably should check the protocol on the request and put it in the response headers. PR welcome ;)

**Comment by aaronpowell** [comment]
And look at that, #39 fixes it! (I also realised it's fine to return a HTTPS location response to HTTP, that won't trigger mixed-mode 😛)
