### ISSUE TITLE
Custom Reponse Body?

### ISSUE THREAD

**Issue by cuongluu8** [Readify/httpstatus#43]
I want to know if it is possible to override the response body with a custom json object?

**Comment by aaronpowell** [comment]
Would this be for a `GET` or a `POST` request, or for any?

For some context the original goal of this website was to plug in different HTTP response statuses to an application and see how it would work (integration tests and the like), and not worry about the payload (`200 OK` testing wasn't the priority).

Custom response bodies do make for an interesting problem, in a `POST` well you could just have whatever is `POST`ed as the body returned, but `GET` is harder, do you abuse query strings? custom headers? something else?

TBH I'm probably not going to have time to look at this but I'm happy to review a PR that targets your use cases.

**Comment by cuongluu8** [comment]
For a GET - for now I just wanted to know if it was at all possible, which you have kind of answered, so thanks.
I think it would be useful to have some sort of way to provide a custom body in the response driven by a queryString I think.
e.g.
`http://httpst.us/202?contentType=json&body=someEncodedJson`

**Comment by aaronpowell** [comment]
If you prove an `Accepts` header that specifies `application/json` you'll get JSON back: https://github.com/Readify/httpstatus/blob/master/src/Teapot.Web/CustomHttpStatusCodeResult.cs#L31

**Comment by gcornacchia** [comment]
I also vote for this feature too, with this scenario:
I put the desired json response body as a base64 string in a request header and then httpstat.us will return the decoded value as a response payload

**Comment by aaronpowell** [comment]
I haven't had bandwidth to tackle this, but if someone wanted to jump on and set a PR I can review
