### ISSUE TITLE
Max. timeout appears to be 3 mins. 50 seconds, not 5 mins.

### ISSUE THREAD

**Issue by mklement0** [Readify/httpstatus#44]
First things first: great service - thank you.

https://httpstat.us/ states:

> the time in ms, max 5 minutes

In practice, the maximum appears to be 3 mins 50 secs., i.e., `230000` ms.

You can verify this as follows in PowerShell:

```powershell
(Measure-Command { Invoke-WebRequest https://httpstat.us/200?sleep=270000  2>&1 | Out-Default }).TotalSeconds
```

**Comment by aaronpowell** [comment]
Well this appears to be a limit of the Azure platform that we host on, see [this forum post](https://social.msdn.microsoft.com/Forums/en-US/05f254a6-9b34-4eb2-a5f7-2a82fb40135f/time-out-after-230-seconds?forum=windowsazurewebsitespreview)

**Comment by aaronpowell** [comment]
I've added a note on the homepage. Given you can choose to host the site yourself (say, you want to test with it inside a DMZ) I didn't drop the max allowed.
