### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by AirQuick** [Readify/httpstatus#46]
https://httpstat.us
> Valid until | Tue, 30 Jan 2018 01:01:30 UTC (expired 1 day, 6 hours ago)  EXPIRED

**Comment by tathamoddie** [comment]
@aaronpowell Looks like the Lets Encrypt job died.

**Comment by aaronpowell** [comment]
Oops, let me get onto that

**Comment by aaronpowell** [comment]
Fixed.
