### ISSUE TITLE
status 302 is missing!! please XD

### ISSUE THREAD

**Issue by joneldiablo** [Readify/httpstatus#50]
hello I'm trying to use the 302 but its return 200

**Comment by valkheim** [comment]
There is a 302 : https://github.com/Readify/httpstatus/blob/master/src/Teapot.Web/Models/StatusCodeResults.cs#L71

```
~ > curl -s -o /dev/null -w "%{http_code}" http://httpstat.us/302  
302%
~ > curl -s -o /dev/null -w "%{http_code}" http://httpstat.us/302 --location
200%
```

You're likely to follow redirect 🙃

**Comment by aaronpowell** [comment]
Closing as the site does support `302` but it will provide you a redirect which you have to abort.
