### ISSUE TITLE
HTTPS Certificate Expired

### ISSUE THREAD

**Issue by jamiebrynes7** [Readify/httpstatus#51]
Accessing `https://httpstat.us/*` gives a security warning error

**Comment by jamiebrynes7** [comment]
![image](https://user-images.githubusercontent.com/13353733/42636221-1f728bce-85e0-11e8-9977-45b7adcf218a.png)

**Comment by aaronpowell** [comment]
Fixed.

I thought the extension was supposed to auto-renew the certificate. Guess not ☹.

**Comment by aaronpowell** [comment]
For the record - I'd installed the Azure extension that didn't have the Web Job included to auto-renew the certificate, whoops!
