### ISSUE TITLE
Return Bad Status Codes

### ISSUE THREAD

**Issue by kevingy** [Readify/httpstatus#52]
_Sometimes_, the real world doesn't conform to standards. While developing SimpleBrowser (https://github.com/SimpleBrowserDotNet/SimpleBrowser), one of our users has reported that SimpleBrowser crashes when a web server returns 0 for an HTTP status code. In looking for a way to test and fix that issue, I found httpstat.us. Unfortunately, when I ask httpstat.us to return a 0 status code, the site says "What you've requested doesn't exist...", which not true. It does exist ... in a web server or application that does exist, but does not conform to standards. It is possible that the response was actually an XMLHtmlRequest (https://fetch.spec.whatwg.org/). Earlier versions of this specification did have a 0 response status code (https://www.w3.org/TR/2014/WD-XMLHttpRequest-20140130/#dom-xmlhttprequest-status).

Is there any chance that the application could be modified to allow for a 0 status code?

**Comment by aaronpowell** [comment]
It'd be possible to do that, we'd just have to change the route constraints (we already return for arbitrary 3-digit codes).

But I'm not sure it would work anyway, most non-standard HTTP codes are blocked by the load balancer (for example, the 1xx codes don't work).
