### ISSUE TITLE
Allow paths after the status code

### ISSUE THREAD

**Issue by petenelson** [Readify/httpstatus#53]
One of the apps I'm working with uses [ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html), and I was adding better support for HTTP errors, so I decided to use httpstatus for my unit tests. The app automatically appends additional paths to the URL to retrieve data from ElasticSearch, so it was trying to access [http://httpstat.us/405/_cat](http://httpstat.us/405/_cat) during testing, but the httpstatus service doesn't support random paths on the end of the URL.

I found a workaround in my code to strip the paths, but If this is something that may be handy in the httpstatus site, I can take a shot at a pull request. It's been a few years since I did any serious ASP.NET work, but it would come back pretty quick.

**Comment by akinsete** [comment]
Waiting for this as well.

**Comment by aaronpowell** [comment]
Closing as I think we added this a while ago (like, the link above works as expected)
