### ISSUE TITLE
Add support for SSL issues

### ISSUE THREAD

**Issue by CGamesPlay** [Readify/httpstatus#55]
httpstat.us is useful, and I think it would be really useful if it also allowed you to debug SSL issues as well. Perhaps something like `invalid-host.httpstat.us` or `expired.httpstat.us` would return an invalid host, or an expired certificate.

If something like this exists elsewhere, I haven't found it.

Thanks for considering!

**Comment by aaronpowell** [comment]
Is your goal to try and make an API call to a URL that has an invalid certificate (expired or otherwise)?

**Comment by webserveis** [comment]
I found this for test SSL https://badssl.com/

**Comment by DasSkelett** [comment]
Hehe, I think the expired cert part got accidentally implemented now, #79
