### ISSUE TITLE
102 Processing seems broken

### ISSUE THREAD

**Issue by skerit** [Readify/httpstatus#69]
I'm trying to see how the 102 works using curl:

```bash
curl -v "https://httpstat.us/102"
```

But I only get this response:

```
> GET /102 HTTP/1.1
> Host: httpstat.us
> User-Agent: curl/7.58.0
> Accept: */*
> 
```

According to the spec, 102 should actually eventually be followed by a valid status code & response, but nothing's coming.

**Comment by neilpalima** [comment]
I encountered this issue as well. 1xx code do not make any response.

**Comment by aaronpowell** [comment]
Unfortunately, Azure doesn't support 1xx status codes very well so it's not possible to have them be reliable. If you're needing to test them, I'd look at how you can run on your own infrastructure.
