### ISSUE TITLE
crossdomain.xml to add support for Flash Player

### ISSUE THREAD

**Issue by stevendesu** [Readify/httpstatus#7]
I ran into a rather interesting issue today that I think you can help me with. I have a Flash video player which loads ads from adap.tv. Today adap.tv did something really odd — their tracking URL returns a 302 (Found) code, with a Location header pointing to httpstat.us/503 ~~(why they don’t simply return a 503 header is beyond me, but presumably a limitation of their system)~~ **Silly pranksters and their secondary tracking URLs**

Unfortunately Flash is not very intelligent about how it handles redirects. A new Loader instance is spun up under the hood for handling the redirect and all events are delegated to the old Loader. As a result I lack the ability to bind listeners to or directly control the Loader after such an event.

In this particular case, Flash was disallowed to read the body of the response since there was no valid crossdomain.xml file. The header returned a Content-Length of 23, however a 0-byte array was returned (since there is not proper permissions for reading the response). When it goes to read 23 bytes from this 0-byte array, it throws an error (“Unexpected End of File”). I’ve done everything I can to try and catch this error myself, however because Flash has a bad habit of secretly spinning up new instances of classes and not giving access to them, I am unable to. For the time being my work-around has been to detect the status code before the error is thrown, increment a global counter, then have a global handler for uncaught errors which checks this counter to see if the crash was expected.

Would it be possible to add a crosdomain.xml file to httpstat.us? It would both allow me to avoid the global error handler nonsense, and it would make your service accessible to ActionScript developers wishing to test how their program responds to different status codes.

**Comment by aaronpowell** [comment]
Not only has this issue been inactive for a long time, [Flash well and truly dead](https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html) so I'm closing this out.
