### ISSUE TITLE
Support build with Mono

### ISSUE THREAD

**Issue by patsevanton** [Readify/httpstatus#74]
```
dotnet --version
3.0.100
```

Cd src in repo httpstatus
```
ls
Teapot.sln  Teapot.Web
```

Build:

```
dotnet build
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Nothing to do. None of the projects specified contain packages to restore.
/root/httpstatus/src/Teapot.Web/Teapot.Web.csproj(145,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/3.0.100/Microsoft/VisualStudio/v16.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Build FAILED.

/root/httpstatus/src/Teapot.Web/Teapot.Web.csproj(145,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/3.0.100/Microsoft/VisualStudio/v16.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.43
```

**Comment by mderriey** [comment]
This is not an ASP.NET Core application, so you won't be able to build it with the .NET Core SDK.

You'll need Visual Studio or the desktop version of MSBuild to build it.
It _might_ build with Mono on Linux, but we didn't do anything special to support it, so you could run into issues.

**Comment by patsevanton** [comment]
Thanks for answer
May be change issue to "Support build with Mono" ?

**Comment by mderriey** [comment]
Did you try building the app with Mono? If so, did you face an issue?

To be honest, I don't think we want to spend time looking at this.
My opinion is that the next move we would make (if we decide to make one) is to port the app to ASP.NET Core, so researching how to build the app on Mono would be pretty low on the list.

Another option for you might be to create a free Azure DevOps organization which offers 1,800 minutes of free CI/CD pipelines. Azure DevOps provides Windows-based agents, so you wouldn't have to look into this if you don't want to.

**Comment by aaronpowell** [comment]
Moved to .NET 6 which is cross platform so this is no longer relevant
