### ISSUE TITLE
Domain not resolving

### ISSUE THREAD

**Issue by shaneog** [Readify/httpstatus#76]
The domain is not resolving so the site is offline:

```sh
dig A httpstat.us

; <<>> DiG 9.10.6 <<>> A httpstat.us
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3320
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;httpstat.us.                   IN      A

;; AUTHORITY SECTION:
us.                     899     IN      SOA     a.cctld.us. hostmaster.neustar.biz. 2026253498 900 900 604800 86400

;; Query time: 70 msec
;; SERVER: 10.250.0.254#53(10.250.0.254)
;; WHEN: Mon Feb 03 11:14:10 PST 2020
;; MSG SIZE  rcvd: 106

```

**Comment by Rj7** [comment]
Same here!

**Comment by mderriey** [comment]
Hey 👋

Thanks for reporting this, we'll look into it.

Cheers

**Comment by ahosie** [comment]
`Checking server [whois.nic.us]
Results:
Domain Name: httpstat.us
Registry Domain ID: D31783408-US
Registrar WHOIS Server: whois.101domain.com
Registrar URL: www.101domain.com
Updated Date: 2020-02-03T00:13:55Z
Creation Date: 2011-02-03T02:36:29Z
Registry Expiry Date: 2020-02-02T23:59:59Z`

**Comment by RobFaie** [comment]
The domain belongs to a former employee and I have been working with them to get the domain transferred over to us, but things didn't quite fall into place in time.

We're working on getting it renewed and getting everything back up and running.

I do apologize for the downtime here.

**Comment by RobFaie** [comment]
We're back live! Thanks for flagging this and please do let us know if you have any further issues.

Again I apologize for the downtime.
