### ISSUE TITLE
https://httpstat.us/ - SSL Certificate expires

### ISSUE THREAD

**Issue by asdf913** [Readify/httpstatus#79]
https://www.ssllabs.com/ssltest/analyze.html?d=httpstat.us
![image](https://user-images.githubusercontent.com/2301325/87294465-6e709800-c536-11ea-868e-4be50f19e151.png)

**Comment by RobFaie** [comment]
Hi,

Thanks for calling this out. As you may or not be aware this site is actually hosted by a former employee and we haven't gotten around to moving it over to our infrastructure, so this isn't the simplest of problems for us to fix right this minute.

I have enabled Cloudflare Proxy as a temporary fix while we work with Aaron to either get a new Let's Encrypt cert or move the site to our hosting.

Will keep you posted.

**Comment by asdf913** [comment]
Thanks you for your quick response.

**Comment by xinz** [comment]
Hello @RobFaie,

Thanks for your help, I find that after enable Cloudflare Proxy, this tool set website is using HTTP/2 now, is it possible revert it back to HTTP/1.1 as original?
