### ISSUE TITLE
http://httpstat.us/200 return 403 (FORBIDDEN) when Java call the URL

### ISSUE THREAD

**Issue by asdf913** [Readify/httpstatus#80]
**Testing program**

```
public class SslTest{

	public static void main(String[] args) throws java.io.IOException {
		 new java.net.URL("http://httpstat.us/200").openConnection().getInputStream();
	}
	
}
```

**Output**
>Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://httpstat.us/200
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at SslTest.main(SslTest.java:4)

**Comment by denilsonsa** [comment]
I've faced the exact same issue with Python:

    urllib.request.urlopen('http://httpstat.us/200')

The solution is to pass a `User-Agent` header. Additionally, if you want to have any body response, also pass the `Accept` header.

    req = Request('http://httpstat.us/200', headers={
        'Accept': 'text/plain',
        'User-Agent': 'Anything here',
    })
    return urllib.request.urlopen(req)

Alternatively, you could use a library such as `requests` instead of the lower level `urllib`.

**Comment by asdf913** [comment]
> I've faced the exact same issue with Python:
> 
> ```
> urllib.request.urlopen('http://httpstat.us/200')
> ```
> 
> The solution is to pass a `User-Agent` header. Additionally, if you want to have any body response, also pass the `Accept` header.
> 
> ```
> req = Request('http://httpstat.us/200', headers={
>     'Accept': 'text/plain',
>     'User-Agent': 'Anything here',
> })
> return urllib.request.urlopen(req)
> ```
> 
> Alternatively, you could use a library such as `requests` instead of the lower level `urllib`.

The testing program is updated , based on your comment.
The **http://httpstat.us/200* return **0 K** is **User-Agent** is set in **request** header.

```
import java.net.HttpURLConnection;

public class SslTest {

	public static void main(String[] args) throws java.io.IOException {
		//
		final java.net.URLConnection urlConnection = new java.net.URL("http://httpstat.us/200").openConnection();
		//
		if (urlConnection instanceof HttpURLConnection) {
			final HttpURLConnection httpURLConnection = (HttpURLConnection) urlConnection;
			httpURLConnection.setRequestProperty("User-Agent", "");
		}
		//
		try (final java.io.InputStream is = urlConnection != null ? urlConnection.getInputStream() : null;
				final java.io.Reader r = new java.io.InputStreamReader(is)) {
			while (r.read() != -1) {
				System.out.print((char) r.read());
			}
		}
		//
	}

}
```

**Comment by denilsonsa** [comment]
> The *_http://httpstat.us/200_ return **0 K** is **User-Agent** is set in **request** header.

The lack of `User-Agent` header causes a *403 Fobidden* error.

Returning a zero-length body response is not an error (in fact, it returned *200 OK*). You have to also add an `Accept` header to get anything in the response body.

Regardless, I have to agree the behavior related to these two headers is not documented anywhere in <http://httpstat.us/>, and it would be great if it was documented.

**Comment by mike-hurley-rally** [comment]
Since people can put anything in the user agent, I'd suggest taking that guard out.

**Comment by iansedano** [comment]
Using fiddler I found that there is a default User-Agent, `Python-urllib/3.10` that is sent with `urllib.request`, here is the default raw HTTP message:

```http
GET https://httpstat.us/200 HTTP/1.1
Accept-Encoding: identity
Host: httpstat.us
User-Agent: Python-urllib/3.10
Connection: close
```

Whereas if I set the `User-Agent` to `""` (a blank string), I get a 200 OK response. Not sure if that is accurate or I am reading something wrong.

Here is the Python 3.10.0 code using the default settings:

```py
import urllib.error
import urllib.request


def make_request(url):
    print("Starting request")
    try:
        response = urllib.request.urlopen(url)
    except urllib.error.HTTPError as e:
        print(e.status, e.reason)
    else:
        print(response.status)
        return response
    finally:
        print("Done!")

httpstat_response = make_request("https://httpstat.us/200")
```

This gives a 403.

Here is the modification that gets the 200 response:

```diff
# ...

    print("Starting request")
+   request = urllib.request.Request(url, headers={"User-Agent": ""})
    try:
-       response = urllib.request.urlopen(url)
+       response = urllib.request.urlopen(request)
    except urllib.error.HTTPError as e:

# ...
```

Which sends a raw HTTP message of:

```http
GET https://httpstat.us/200 HTTP/1.1
Accept-Encoding: identity
Host: httpstat.us
User-Agent: 
Connection: close
```

**Comment by aaronpowell** [comment]
@iansedano I've just deployed a rewritten version on .NET 6 (rather than .NET Framework). Are you able to test if this is still a problem?

**Comment by asdf913** [comment]
> @iansedano I've just deployed a rewritten version on .NET 6 (rather than .NET Framework). Are you able to test if this is still a problem?

It is okay for Java Program (i.e. httpURLConnection.setRequestProperty("User-Agent", "");)

**Comment by iansedano** [comment]
The code above now gets a 200 response without having to change the UA, thanks!
