### ISSUE TITLE
Enabling CORS on error 429 doesn't allow Retry-After header

### ISSUE THREAD

**Issue by parsley72** [Readify/httpstatus#83]
You're setting Retry-After for error 429 but enabling CORS doesn't add Access-Control-Allow-Headers for Retry-After so I can't read it from within a browser.

**Comment by parsley72** [comment]
You're setting Retry-After for error 429 but enabling CORS doesn't add Access-Control-Allow-Headers for Retry-After so I can't read it from within a browser.

**Comment by parsley72** [comment]
I figured out from the code that I can sent a GET to https://httpstat.us/429/cors with the header "Access-Control-Request-Headers" = "Retry-After" then it'll add "Access-Control-Allow-Headers" = "Retry-After" to the response, but I'm not allowed to do this from the browser so it doesn't help.

**Comment by mderriey** [comment]
> but I'm not allowed to do this from the browser so it doesn't help.

What do you mean by this? As in, you type the URL in your browser?

**Comment by parsley72** [comment]
No, I mean I'm writing a website in ReactJS. When I try to add custom headers like this:

```
import axios from 'axios'

    let local_fetch = axios.create({
        baseURL: 'https://httpstat.us',
    })

    local_fetch({
        url: '/429/cors',
        method: 'get',
        headers: { 'Access-Control-Request-Headers': 'Retry-After' }
    })
        .then(res => {
            console.log(res)
        })
        .catch(e => {
            console.log(e.response)
        })
```
I get "xhr.js:132 Refused to set unsafe header "Access-Control-Request-Headers". This is coming from the spec for XMLHttpRequest:
https://xhr.spec.whatwg.org/#dom-xmlhttprequest-setrequestheader
"Access-Control-Request-Headers" is a forbidden header name:
https://fetch.spec.whatwg.org/#forbidden-header-name

So this works fine from cURL or Postman but can't be used within JS.

**Comment by mderriey** [comment]
OK, got it.

Apologies, I didn't read the whole thing properly.

I looked at your implementation and noticed a few issues:

- If the request sends a `Access-Control-Request-Headers`, then two `Access-Control-Allow-Headers` will be added to the response;
- There's also no check about duplicate headers.

I tried to push to your branch but couldn't.
I think when you open a PR, you can specify whether contributors of the target repository can push to your fork.
Would you mind enabling this? Otherwise I'll open a PR on top of your PR, but it sounds like overkill.

Cheers.

**Comment by parsley72** [comment]
"Allow edits by maintainers" is checked, is that what you mean?

**Comment by mderriey** [comment]
> "Allow edits by maintainers" is checked, is that what you mean?

Ah yes, turns out I was doing it wrong...
I successfully pushed to your branch, so I'll decline your invitation, but thanks for your promptness!

**Comment by parsley72** [comment]
Minor point - would be good to add some instructions on how to run this locally, I don't have enough experience of CS to know how to do this.

**Comment by mderriey** [comment]
This is an old .NET framework-based solution, so unfortunately you'll need Visual Studio.

However, there are no dependencies, so you would only need to open the solution, start the web project, and off you go.

**Comment by parsley72** [comment]
I tried that with VS2019 and got an error. I'll get a clean repo and try again.

**Comment by parsley72** [comment]
Has the change been released yet?

**Comment by mderriey** [comment]
Yes.

**Comment by parsley72** [comment]
Seeing it on curl:
`$ curl -I https://httpstat.us/429/cors
HTTP/2 429 
date: Mon, 14 Sep 2020 22:56:23 GMT
content-type: text/plain; charset=utf-8
content-length: 21
set-cookie: __cfduid=da8f183f9bd323d2991a136e00f6155191600124183; expires=Wed, 14-Oct-20 22:56:23 GMT; path=/; domain=.httpstat.us; HttpOnly; SameSite=Lax
cache-control: private
retry-after: 5
x-aspnetmvc-version: 5.1
access-control-allow-origin: *
access-control-allow-headers: Retry-After
x-aspnet-version: 4.0.30319
request-context: appId=cid-v1:7585021b-2db7-4da6-abff-2cf23005f0a9
access-control-expose-headers: Request-Context
x-powered-by: ASP.NET
set-cookie: ARRAffinity=c529441eca9a1f7cff05208d4b61553ecda3678bc13876939acfd3b19b1183c2;Path=/;HttpOnly;Domain=httpstat.us
cf-cache-status: DYNAMIC
cf-request-id: 05306e7bb00000fb84bfa21200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5d2db372bd91fb84-AKL`

but still not working from the browser.

**Comment by parsley72** [comment]
Browser example: https://codesandbox.io/s/get-retry-after-from-httpstatus-wgyf6

**Comment by parsley72** [comment]
My mistake - I should have used `Access-Control-Expose-Headers` instead of `Access-Control-Allow-Headers`. Submitting a new PR now.

**Comment by parsley72** [comment]
@mderriey ?

**Comment by mderriey** [comment]
I was on leave last week. I merged your PR, thanks.

**Comment by parsley72** [comment]
Working now, thanks.
