### ISSUE TITLE
sleep option doesn't respect delay over 1 minute 40 seconds

### ISSUE THREAD

**Issue by ruebrenda** [Readify/httpstatus#92]
My command is `curl httpstat.us/200?sleep=120000` (sleep for 2 mins). Sometimes I get back a valid response at 2 minutes. But more often than not, I get back `524 Origin Time-out` at 1 minute 40 seconds.

The documentation seems to indicate it supports 230 seconds (3 mins 50 seconds).

**Comment by aaronpowell** [comment]
Sleep is pretty unreliable, and due to the abuse identified in diagnosing #89, it's now more intentionally unreliable.

**Comment by ruebrenda** [comment]
@aaronpowell Thanks for the quick answer. Might be useful to other consumers to add a note to the doc page at https://httpstat.us/.
